PoterieJoelleHenault/Controllers/TextesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PoterieJoelleHenault.Models;

namespace PoterieJoelleHenault.Controllers
{

    [Authorize]
    public class TextesController : Controller
    {
        private PoterieDB db = new PoterieDB();

        public ActionResult Index()
        {
            return View(db.Textes.ToList());
        }

        public ActionResult Details(int id = 0)
        {
            Textes textes = db.Textes.Find(id);
            if (textes == null)
            {
                return HttpNotFound();
            }
            return View(textes);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Textes textes)
        {
            if (ModelState.IsValid)
            {
                db.Textes.Add(textes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(textes);
        }

        public ActionResult Edit(int id = 0)
        {
            Textes textes = db.Textes.Find(id);
            if (textes == null)
            {
                return HttpNotFound();
            }
            return View(textes);
        }

        [HttpPost]
        public ActionResult Edit(Textes textes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(textes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(textes);
        }

        public ActionResult Delete(int id = 0)
        {
            Textes textes = db.Textes.Find(id);
            if (textes == null)
            {
                return HttpNotFound();
            }
            return View(textes);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Textes textes = db.Textes.Find(id);
            db.Textes.Remove(textes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

PoterieJoelleHenault/Views/Admin/Index.cshtml
@model PoterieJoelleHenault.Models.User

@{
    ViewBag.Title = "Module administratif";
}

<h2>@ViewBag.Title</h2>

@{if (!Request.IsAuthenticated)
  {
    using (Html.BeginForm()) {
        Html.ValidationSummary(true);

        <fieldset>
            <legend>User</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.Username)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Username)
                @Html.ValidationMessageFor(model => model.Username)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Password)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>

            <p>
                <input type="submit" value="Log In" />
            </p>
        </fieldset>
    }
  }
  else
  {
      <nav id="menuGalery">
          <ol>
              <li>
                  @Html.ActionLink("Gérer les items de la galerie", "List", "Galerie")
              </li>
              <li>
                  @Html.ActionLink("Gérer les textes", "Index", "Textes")
              </li>
          </ol>
      </nav>
  }
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}